## EDA

In [1]:
import pandas as pd
data_train = pd.read_csv("/Users/jonathan.sierks/01_Uni/10_DataMining/expedia-hotel-ranking/data/training_set_VU_DM.csv")
data_train.head(5)

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,893,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,10404,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,21315,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,27348,2,4.0,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
4,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,29604,4,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

In [2]:
df = data_train.copy()

In [3]:
df[df.click_bool == True].srch_id.count()

221879

In [1]:
df[df.booking_bool == True].srch_id.count()

NameError: name 'df' is not defined

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df[df.booking_bool == True][:100]

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,position,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,orig_destination_distance,random_bool,comp1_rate,comp1_inv,comp1_rate_percent_diff,comp2_rate,comp2_inv,comp2_rate_percent_diff,comp3_rate,comp3_inv,comp3_rate_percent_diff,comp4_rate,comp4_inv,comp4_rate_percent_diff,comp5_rate,comp5_inv,comp5_rate_percent_diff,comp6_rate,comp6_inv,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
12,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,68914,2,3.0,1,2.20,0.0206,4.44,13,100.89,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,11.0,1,114.29,1
63,6,2013-06-05 12:27:51,14,100,NaN,NaN,100,104251,3,4.0,1,1.95,NaN,0.00,1,145.00,0,21106,1,5,2,0,1,0,NaN,652.84,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,162.38,1
68,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,27669,3,3.5,1,3.00,0.2107,4.62,16,85.00,0,7082,1,0,1,0,1,0,NaN,4.17,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,96.41,1
194,21,2013-02-18 17:16:25,15,55,NaN,NaN,216,61662,3,3.5,0,4.04,0.5370,4.54,4,47.94,1,18161,4,62,1,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,-1.0,0.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,222.58,1
211,25,2012-12-11 13:03:42,5,219,NaN,NaN,219,23228,4,4.0,0,3.26,0.3676,4.44,22,42.00,1,3735,1,0,2,0,1,0,NaN,767.86,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,47.10,1
243,28,2012-11-26 10:13:17,5,219,NaN,NaN,219,13996,4,4.0,1,2.89,0.0491,5.07,26,85.00,0,24232,3,27,1,0,1,0,NaN,116.14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,9.0,1,286.32,1
274,29,2013-02-26 19:42:22,18,129,NaN,NaN,219,1722,3,4.0,0,5.72,0.1136,5.81,1,248.17,1,5143,6,144,5,0,1,0,NaN,3748.90,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1927.64,1
312,30,2013-02-11 01:28:38,24,216,NaN,NaN,219,125611,3,3.5,1,4.55,0.2653,5.63,13,176.98,1,20319,9,13,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,1831.30,1
346,36,2013-04-03 08:54:17,22,92,NaN,NaN,219,15181,3,4.0,1,1.61,0.1784,4.88,4,101.51,0,2715,2,11,1,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,226.76,1
387,39,2013-04-06 18:08:58,5,219,NaN,NaN,219,109855,2,3.5,1,1.10,0.3217,4.05,1,55.00,0,24361,1,7,2,2,1,1,NaN,53.92,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,60.77,1
428,42,2012-12-19 14:24:00,14,100,NaN,NaN,100,61713,2,4.0,1,0.00,0.2079,5.13,1,108.21,0,5740,1,87,2,0,1,1,NaN,57.57,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,122.34,1
467,44,2013-03-19 15:57:46,15,55,NaN,NaN,55,13205,4,4.5,0,5.14,0.1550,5.46,1,126.83,1,24752,1,1,1,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,42.0,NaN,NaN,NaN,1.0,0.0,42.0,NaN,NaN,NaN,1,126.89,1
509,45,2013-05-18 09:25:08,14,100,NaN,NaN,219,88719,2,2.0,1,1.39,0.0492,4.45,8,60.31,1,10948,1,0,2,0,1,1,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,60.95,1
543,46,2013-05-01 10:55:11,5,77,NaN,NaN,30,90440,4,4.5,1,2.30,0.0695,6.18,3,209.00,0,1995,3,21,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,744.54,1
568,47,2013-01-14 22:28:43,14,100,4.31,180.75,137,77040,4,4.0,0,3.14,0.0839,5.39,16,153.50,0,13901,6,3,1,1,1,0,NaN,5593.11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,924.00,1
586,49,2013-02-07 18:40:10,16,31,2.50,270.08,31,13962,4,4.5,1,6.42,0.7886,5.43,4,115.24,0,2799,1,5,2,0,1,0,NaN,144.11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1,128.48,1
624,52,2013-06-09 09:22:16,16,31,NaN,NaN,215,59239,3,4.5,1,3.95,0.2304,0.00,15,60.80,0,23641,2,7,1,0,1,0,NaN,974.25,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,1,149.35,1
653,53,2013-02-13 07:00:24,5,219,NaN,NaN,219,101178,4,4.5,1,3.91,0.1399,5.35,4,151.00,1,7434,2,16,2,0,1,1,NaN,0.29,0,NaN,NaN,NaN,1.0,0.0,37.0,1.0,0.0,11.0,NaN,NaN,NaN,-1.0,0.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,17.0,1,347.65,1
690,57,2013-04-11 10:42:23,16,31,NaN,NaN,31,119428,3,4.5,0,3.04,0.0849,4.93,1,69.44,0,1074,4,13,2,0,1,0,NaN,67.62,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,319.96,1
693,60,2013-04-14 18:36:46,32,220,NaN,NaN,219,10642,3,4.5,1,1.79,0.0085,5.05,7,182.83,0,23904,3,83,2,1,1,1,NaN,7956.58,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,670.49,1
773,64,2012-12-27 11:33:34,5,219,NaN,NaN,219,98884,2,2.5,0,2.30,0.0084,4.64,4,90.00,0,15146,1,2,2,0,1,1,NaN,79.57,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,110.30,1
826,66,2013-03-04 20:44:30,5,219,NaN,NaN,219,35202,3,4.5,1,2.71,NaN,4.80,12,84.00,0,5483,1,18,2,0,1,1,-25.8023,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,96.39,1
853,67,2013-02-28 11:32:25,32,220,NaN,NaN,117,66227,4,3.5,0,4.42,0.0421,4.43,2,72.52,1,1588,2,5,1,1,2,0,NaN,5010.81,0,NaN,NaN,NaN,0.0,0.0,6.0,1.0,0.0,6.0,0.0,0.0,6.0,1.0,0.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,167.41,1
899,72,2013-04-18 13:33:53,5,219,NaN,NaN,219,53494,4,4.0,1,5.80,0.4024,6.10,24,349.00,0,24700,4,47,2,1,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,1,1650.36,1
931,73,2013-03-28 22:09:18,31,219,NaN,NaN,219,121991,3,4.0,1,2.30,0.1467,5.04,8,94.00,1,26172,4,50,2,0,1,1,NaN,2559.42,0,NaN,NaN,NaN,1.0,0.0,8.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,8.0,1,864.78,1
944,74,2013-05-11 12:39:09,5,219,NaN,NaN,219,64949,4,4.5,1,4.08,0.0729,5.54,2,139.00,0,11235,1,6,2,0,1,1,-12.8249,2261.97,0,NaN,NaN,NaN,0.0,0.0,43.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,156.73,1
988,75,2013-05-04 19:20:52,5,219,NaN,NaN,219,128481,4,4.5,0,2.94,0.0434,5.31,22,155.00,0,17311,1,30,3,1,1,0,NaN,318.52,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,165.00,1
1022,78,2012-12-21 05:30:35,5,205,NaN,NaN,15,140297,4,3.5,0,4.62,0.0243,5.07,13,116.00,0,8660,1,6,1,1,2,1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,196.02,1
1054,79,2013-04-07 14:17:02,14,100,NaN,NaN,56,135578,4,4.5,0,4.82,0.0571,5.28,1,108.10,1,16822,3,74,2,0,1,1,NaN,3996.72,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,355.22,1
1082,80,2013-01-03 10:58:19,5,219,2.50,122.34,219,107761,4,3.5,1,2.64,0.5445,4.99,4,127.00,0,7274,2,24,1,0,1,0,NaN,386.87,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,6.0,1,324.08,1
1129,82,2013-02-18 11:42:06,5,219,NaN,NaN,216,95527,5,4.5,0,2.83,NaN,5.87,1,251.00,1,27275,2,47,2,0,1,1,-14.0930,5509.40,0,NaN,NaN,NaN,1.0,0.0,64.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,623.50,1
1165,84,2013-04-12 17:19:01,5,219,NaN,NaN,129,2499,4,4.5,0,2.56,0.1194,5.00,2,178.00,0,7687,4,172,2,0,1,0,NaN,4791.25,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,760.66,1
1197,85,2013-02-28 06:33:47,14,100,NaN,NaN,219,90679,2,4.0,1,1.61,0.1338,4.78,3,94.12,0,2346,1,1,2,0,1,1,NaN,126.31,0,NaN,NaN,NaN,-1.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,104.75,1
1206,87,2013-05-15 18:22:23,16,31,3.74,210.60,31,33406,4,4.0,1,0.69,0.5935,4.79,2,96.65,0,26262,1,3,1,0,1,1,NaN,166.25,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,33.0,0.0,0.0,NaN,0.0,0.0,16.0,NaN,-1.0,NaN,1,96.90,1
1286,93,2013-01-18 14:55:16,5,219,NaN,NaN,99,104086,4,4.0,0,4.28,0.0065,5.29,9,164.00,1,13292,4,26,2,0,2,0,NaN,3453.80,0,1.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,8.0,NaN,NaN,NaN,1,1402.60,1
1308,94,2013-01-04 11:34:46,5,219,NaN,NaN,219,63271,3,4.0,1,1.95,0.1587,4.77,14,80.00,0,11966,2,26,2,2,1,0,NaN,106.97,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,209.50,1
1363,97,2012-11-19 07:33:00,5,219,NaN,NaN,219,31359,4,4.0,0,4.69,0.2815,5.47,14,264.00,1,17759,1,6,2,0,1,0,NaN,206.23,0,NaN,NaN,NaN,1.0,0.0,11.0,-1.0,1.0,11.0,NaN,NaN,NaN,-1.0,0.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,11.0,1,326.95,1
1397,99,2013-02-18 16:22:13,5,219,NaN,NaN,219,45953,4,4.0,1,2.48,NaN,4.95,4,129.00,0,12964,1,5,1,0,1,1,NaN,198.92,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,145.65,1
1448,101,2013-02-18 17:59:17,12,99,NaN,NaN,219,134331,3,4.0,0,3.09,0.0732,5.45,22,222.96,1,27620,1,74,4,1,2,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,490.36,1
1465,102,2012-12-31 16:20:08,5,219,NaN,NaN,219,75137,3,4.0,1,1.61,0.0434,4.52,15,75.00,0,18017,2,1,2,0,1,0,NaN,326.31,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,168.12,1
1493,104,2013-05-10 00:01:48,14,100,NaN,NaN,100,10243,3,5.0,1,1.39,0.1419,5.20,2,142.57,0,3004,3,76,2,1,1,1,NaN,1008.45,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,499.22,1
1503,106,2013-06-17 09:20:02,5,219,NaN,NaN,219,39675,3,4.5,0,2.56,0.4089,0.00,2,180.00,1,25427,1,24,2,2,1,1,NaN,155.61,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,171.64,1
1596,110,2013-03-09 11:16:54,5,219,NaN,NaN,219,131920,3,4.0,0,2.71,0.1415,4.49,15,79.00,0,22097,1,23,3,3,2,0,NaN,269.70,1,NaN,NaN,NaN,1.0,0.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,174.68,1
1618,111,2013-04-01 11:09:26,24,216,NaN,NaN,219,97574,2,2.5,1,3.91,0.1258,4.96,15,128.54,1,27770,4,23,2,1,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,578.73,1
1639,112,2013-04-18 13:12:26,5,219,NaN,NaN,219,84285,3,3.0,1,1.10,0.0771,4.40,3,83.00,0,18584,3,2,1,0,1,1,NaN,1637.75,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,274.14,1
1672,113,2012-11-20 11:06:17,23,181,3.89,137.25,181,97028,4,4.0,1,3.47,0.2863,4.91,12,170.25,0,3531,1,2,1,0,1,1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,7.0,NaN,NaN,NaN,1,191.79,1
1713,114,2013-04-02 08:20:10,5,219,NaN,NaN,219,135081,3,4.5,1,2.71,0.1521,4.99,2,103.00,0,23105,1,235,2,0,1,1,NaN,176.47,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,119.53,1
1716,115,2013-03-28 18:08:52,5,219,NaN,NaN,219,27980,2,4.0,1,2.56,0.3507,4.41,1,99.00,0,16765,1,70,2,2,1,1,NaN,525.29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,107.42,1
1736,116,2012-11-29 16:08:37,14,100,NaN,NaN,100,69327,3,3.5,1,2.40,0.2242,5.35,19,103.78,0,21087,2,1,2,0,1,1,NaN,194.98,0,NaN,NaN,NaN,1.0,0.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,253.88,1
1753,117,2013-04-25 10:34:31,5,219,NaN,NaN,219,56740,4,4.5,1,1.39,NaN,5.61,20,299.00,0,1515,1,2,2,0,1,1,NaN,79.48,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,258.58,1
1786,118,2013-06-17 21:08:27,5,219,NaN,NaN,219,86727,3,4.5,1,3.04,NaN,0.00,21,99.00,0,13502,3,31,2,2,1,1,NaN,278.46,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,439.77,1
1812,120,2013-01-06 10:22:49,5,219,NaN,NaN,219,25476,4,3.5,1,5.31,0.3027,5.75,4,159.00,0,15748,1,3,2,0,1,0,NaN,110.69,0,NaN,NaN,NaN,0.0,0.0,12.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,24.0,1,185.96,1
1852,123,2013-05-09 20:20:41,5,219,NaN,NaN,219,105781,3,4.0,1,1.39,NaN,4.53,20,66.00,0,15265,1,2,2,0,1,1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,71.82,1
1865,124,2012-12-21 12:53:27,5,219,NaN,NaN,219,15174,3,4.0,1,3.78,0.1379,4.94,10,80.00,1,4182,1,1,1,1,1,1,NaN,704.97,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,585.60,1
1946,128,2013-02-11 06:26:05,14,100,NaN,NaN,219,71181,3,3.5,0,5.95,0.1664,5.52,2,160.23,1,4562,3,80,2,0,1,1,NaN,342.29,0,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,11.0,NaN,NaN,NaN,0.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,512.70,1
1979,129,2013-01-16 06:56:51,5,35,NaN,NaN,35,113958,3,3.5,0,3.85,0.1531,4.08,12,35.00,1,21207,2,1,1,0,1,1,NaN,NaN,0,NaN,NaN,NaN,1.0,0.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,78.34,1
1999,131,2012-12-25 11:04:44,9,59,NaN,NaN,219,75694,2,4.0,1,1.61,0.0198,4.16,14,71.98,0,20596,2,0,4,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,161.20,1
2092,135,2013-02-13 14:55:10,5,219,NaN,NaN,219,124466,3,4.5,1,2.30,0.0131,4.86,2,137.00,0,16570,4,44,1,1,2,1,NaN,329.48,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,622.58,1
2185,143,2013-05-22 08:23:23,5,219,NaN,NaN,219,129378,3,4.0,1,3.33,0.2995,4.87,6,129.00,0,20193,1,0,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,-1.0,0.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,280.24,1
2190,144,2013-04-01 10:17:06,5,59,NaN,NaN,219,500,3,4.5,1,2.71,NaN,4.88,12,114.00,0,16863,2,3,2,2,1,1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,259.92,1
2242,146,2013-02-06 13:52:27,5,219,NaN,NaN,219,74728,3,3.5,0,3.64,0.2209,5.26,4,194.00,0,18321,2,1,1,0,1,1,NaN,278.77,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,435.54,1
2322,151,2013-06-09 15:26:42,26,39,NaN,NaN,202,103654,4,3.0,0,0.69,0.0742,0.00,3,151.33,1,4851,1,20,5,0,2,1,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,-1.0,0.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,496.05,1
2431,159,2013-05-08 06:44:22,5,219,NaN,NaN,219,132714,3,4.5,1,0.69,0.2286,5.06,2,169.00,0,28323,4,5,2,0,2,0,NaN,769.31,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,1497.28,1
2508,163,2013-04-14 19:23:27,5,219,NaN,NaN,219,131159,0,4.5,0,1.79,0.6848,4.66,1,119.00,0,15471,1,13,2,0,1,1,NaN,127.85,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,129.00,1
2526,165,2013-02-25 15:00:46,7,100,NaN,NaN,219,50215,4,4.5,0,3.83,0.2486,5.07,1,94.52,1,22997,2,59,2,1,1,1,-37.4457,2301.45,0,NaN,NaN,NaN,0.0,0.0,9.0,-1.0,0.0,9.0,NaN,NaN,NaN,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9.0,1,242.78,1
2556,168,2013-01-04 10:27:26,12,99,NaN,NaN,132,59978,3,4.0,0,5.63,0.6682,5.23,29,91.48,0,27231,1,5,1,0,1,0,NaN,NaN,0,1.0,0.0,6.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1.0,0.0,6.0,1,96.56,1
2588,170,2013-03-07 18:13:21,5,219,NaN,NaN,219,55267,3,4.5,1,1.10,NaN,5.04,21,94.00,0,17100,3,7,2,1,1,1,NaN,358.22,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,40.0,1,327.99,1
2616,174,2013-05-17 08:03:22,5,219,NaN,NaN,219,40738,4,4.0,1,1.61,0.0340,5.41,2,189.00,0,19521,2,11,1,0,1,0,NaN,665.79,0,NaN,NaN,NaN,1.0,0.0,47.0,1.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,21.0,1,426.98,1
2662,175,2013-05-29 12:29:11,14,100,NaN,NaN,100,78541,4,4.5,1,2.56,0.0038,5.07,20,124.63,0,6792,1,3,2,1,1,1,NaN,38.82,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,143.31,1
2830,181,2013-01-21 09:44:20,31,219,NaN,NaN,219,2205,2,4.0,1,0.69,0.0273,4.49,12,63.00,1,27172,1,39,2,0,1,1,NaN,148.36,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,70.72,1
2880,183,2013-02-06 16:54:54,5,219,NaN,NaN,219,94632,3,3.5,0,2.30,0.1840,4.72,15,139.00,0,8254,2,16,2,0,1,1,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,301.66,1
2898,184,2013-06-25 11:59:56,18,129,3.50,334.43,219,136797,2,4.0,0,1.61,0.4388,0.00,1,185.77,0,24483,1,46,2,1,1,1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,206.74,1
2909,185,2013-06-28 05:37:16,5,219,NaN,NaN,127,106817,4,4.0,0,2.08,0.5183,0.00,1,140.00,0,14019,4,10,2,1,1,0,NaN,617.80,0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,25.0,NaN,NaN,NaN,1.0,0.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,808.80,1
2919,187,2013-05-03 03:45:10,5,219,NaN,NaN,100,21150,3,4.0,1,4.60,0.3581,5.03,12,124.00,1,15438,2,23,1,0,1,0,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,165.89,1
2954,188,2012-12-11 07:15:29,15,55,NaN,NaN,55,16730,4,4.5,1,3.95,0.1206,5.17,7,175.64,0,15784,3,13,1,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1,573.95,1
2981,190,2013-05-28 20:12:34,5,219,NaN,NaN,109,8937,5,4.5,0,4.98,NaN,5.26,10,144.00,0,22270,3,22,1,0,1,0,NaN,6903.31,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,462.84,1
3013,192,2013-03-15 12:10:10,5,219,NaN,NaN,219,85363,4,4.0,1,1.95,0.0513,5.03,6,161.00,0,19363,2,13,2,0,1,1,NaN,414.69,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5.0,1,359.90,1
3038,193,2013-02-11 16:12:40,5,219,NaN,NaN,219,106262,4,4.5,0,5.94,0.6835,6.21,3,226.00,1,25459,3,11,2,0,1,1,NaN,186.90,0,NaN,NaN,NaN,0.0,0.0,NaN,1.0,0.0,5.0,NaN,1.0,NaN,1.0,0.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,5.0,1,789.94,1
3051,194,2013-05-22 19:33:08,5,219,NaN,NaN,219,54111,0,4.0,1,3.14,0.2837,4.99,12,182.00,0,1099,5,50,2,0,1,0,NaN,1177.95,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1009.95,1
3100,196,2013-02-05 17:32:52,7,100,NaN,NaN,100,107594,3,4.0,0,1.10,0.3402,5.28,1,115.51,0,19226,3,16,2,0,1,1,NaN,474.61,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,409.96,1
3103,198,2012-12-07 15:46:29,5,219,NaN,NaN,219,4476,3,4.5,1,2.08,0.1019,5.20,3,71.00,0,20757,2,20,2,0,1,1,NaN,421.22,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,11.0,1,163.66,1
3131,199,2012-12-14 20:09:24,14,100,NaN,NaN,100,64414,3,3.5,0,3.69,0.1172,4.95,19,80.16,1,20438,3,44,2,0,1,0,NaN,567.16,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,267.37,1
3147,203,2013-01-03 20:48:24,5,219,NaN,NaN,219,21018,4,4.0,1,3.43,0.1043,5.45,4,169.00,1,8192,3,6,2,0,1,0,NaN,221.67,0,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,1,571.62,1
3157,204,2013-02-18 06:31:41,31,219,NaN,NaN,219,10429,3,4.0,1,1.95,0.5689,5.23,1,207.00,1,2463,2,136,3,1,1,1,NaN,2106.91,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,765.75,1

In [4]:
df.date_time = pd.to_datetime(df.date_time)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4958347 entries, 0 to 4958346
Data columns (total 54 columns):
 #   Column                       Dtype
---  ------                       -----
 0   srch_id                      int64
 1   date_time                    datetime64[us]
 2   site_id                      int64
 3   visitor_location_country_id  int64
 4   visitor_hist_starrating      float64
 5   visitor_hist_adr_usd         float64
 6   prop_country_id              int64
 7   prop_id                      int64
 8   prop_starrating              int64
 9   prop_review_score            float64
 10  prop_brand_bool              int64
 11  prop_location_score1         float64
 12  prop_location_score2         float64
 13  prop_log_historical_price    float64
 14  position                     int64
 15  price_usd                    float64
 16  promotion_flag               int64
 17  srch_destination_id          int64
 18  srch_length_of_stay          int64
 19  srch_booking_window          int64
 20  srch_adults_count            int64
 21  srch_children_count          int64
 22  srch_room_count              int64
 23  srch_saturday_night_bool     int64
 24  srch_query_affinity_score    float64
 25  orig_destination_distance    float64
 26  random_bool                  int64
 27  comp1_rate                   float64
 28  comp1_inv                    float64
 29  comp1_rate_percent_diff      float64
 30  comp2_rate                   float64
 31  comp2_inv                    float64
 32  comp2_rate_percent_diff      float64
 33  comp3_rate                   float64
 34  comp3_inv                    float64
 35  comp3_rate_percent_diff      float64
 36  comp4_rate                   float64
 37  comp4_inv                    float64
 38  comp4_rate_percent_diff      float64
 39  comp5_rate                   float64
 40  comp5_inv                    float64
 41  comp5_rate_percent_diff      float64
 42  comp6_rate                   float64
 43  comp6_inv                    float64
 44  comp6_rate_percent_diff      float64
 45  comp7_rate                   float64
 46  comp7_inv                    float64
 47  comp7_rate_percent_diff      float64
 48  comp8_rate                   float64
 49  comp8_inv                    float64
 50  comp8_rate_percent_diff      float64
 51  click_bool                   int64
 52  gross_bookings_usd           float64
 53  booking_bool                 int64
dtypes: datetime64[us](1), float64(34), int64(19)
memory usage: 2.0 GB

In [6]:
df.describe()

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
count,4.958347e+06,4958347,4.958347e+06,4.958347e+06,251866.000000,252988.000000,4.958347e+06,4.958347e+06,4.958347e+06,4.950983e+06,...,96174.000000,315348.000000,356422.000000,138515.000000,1.916654e+06,1.987503e+06,614730.000000,4.958347e+06,138390.000000,4.958347e+06
mean,1.663666e+05,2013-03-11 06:19:37.890844,9.953133e+00,1.753405e+02,3.374334,176.022659,1.739739e+02,7.007918e+04,3.180525e+00,3.777777e+00,...,17.250473,0.145969,0.083202,19.433267,-6.089936e-02,9.962752e-03,22.430384,4.474858e-02,386.283316,2.791051e-02
min,1.000000e+00,2012-11-01 00:08:29,1.000000e+00,1.000000e+00,1.410000,0.000000,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,...,2.000000,-1.000000,-1.000000,2.000000,-1.000000e+00,-1.000000e+00,2.000000,0.000000e+00,0.000000,0.000000e+00
25%,8.293600e+04,2013-01-14 17:47:32,5.000000e+00,1.000000e+02,2.920000,109.810000,1.000000e+02,3.501000e+04,3.000000e+00,3.500000e+00,...,6.000000,0.000000,0.000000,7.000000,0.000000e+00,0.000000e+00,7.000000,0.000000e+00,124.000000,0.000000e+00
50%,1.665070e+05,2013-03-13 20:13:18,5.000000e+00,2.190000e+02,3.450000,152.240000,2.190000e+02,6.963800e+04,3.000000e+00,4.000000e+00,...,11.000000,0.000000,0.000000,12.000000,0.000000e+00,0.000000e+00,11.000000,0.000000e+00,218.400000,0.000000e+00
75%,2.497240e+05,2013-05-10 00:01:38,1.400000e+01,2.190000e+02,3.930000,213.490000,2.190000e+02,1.051680e+05,4.000000e+00,4.500000e+00,...,18.000000,1.000000,0.000000,20.000000,0.000000e+00,0.000000e+00,17.000000,0.000000e+00,429.790000,0.000000e+00
max,3.327850e+05,2013-06-30 23:58:24,3.400000e+01,2.310000e+02,5.000000,1958.700000,2.300000e+02,1.408210e+05,5.000000e+00,5.000000e+00,...,1620.000000,1.000000,1.000000,9900.000000,1.000000e+00,1.000000e+00,149400.000000,1.000000e+00,159292.380000,1.000000e+00
std,9.611223e+04,NaN,7.646890e+00,6.591625e+01,0.692519,107.254493,6.834525e+01,4.060992e+04,1.051024e+00,1.050329e+00,...,31.160313,0.578202,0.316722,54.370221,4.691723e-01,2.029142e-01,895.965854,2.067514e-01,821.190577,1.647165e-01

In [21]:
pd.isna(df).count()

srch_id                        4958347
date_time                      4958347
site_id                        4958347
visitor_location_country_id    4958347
visitor_hist_starrating        4958347
visitor_hist_adr_usd           4958347
prop_country_id                4958347
prop_id                        4958347
prop_starrating                4958347
prop_review_score              4958347
prop_brand_bool                4958347
prop_location_score1           4958347
prop_location_score2           4958347
prop_log_historical_price      4958347
position                       4958347
price_usd                      4958347
promotion_flag                 4958347
srch_destination_id            4958347
srch_length_of_stay            4958347
srch_booking_window            4958347
srch_adults_count              4958347
srch_children_count            4958347
srch_room_count                4958347
srch_saturday_night_bool       4958347
srch_query_affinity_score      4958347
orig_destination_distance      4958347
random_bool                    4958347
comp1_rate                     4958347
comp1_inv                      4958347
comp1_rate_percent_diff        4958347
comp2_rate                     4958347
comp2_inv                      4958347
comp2_rate_percent_diff        4958347
comp3_rate                     4958347
comp3_inv                      4958347
comp3_rate_percent_diff        4958347
comp4_rate                     4958347
comp4_inv                      4958347
comp4_rate_percent_diff        4958347
comp5_rate                     4958347
comp5_inv                      4958347
comp5_rate_percent_diff        4958347
comp6_rate                     4958347
comp6_inv                      4958347
comp6_rate_percent_diff        4958347
comp7_rate                     4958347
comp7_inv                      4958347
comp7_rate_percent_diff        4958347
comp8_rate                     4958347
comp8_inv                      4958347
comp8_rate_percent_diff        4958347
click_bool                     4958347
gross_bookings_usd             4958347
booking_bool                   4958347
dtype: int64

In [26]:
df.isna().sum()

srch_id                              0
date_time                            0
site_id                              0
visitor_location_country_id          0
visitor_hist_starrating        4706481
visitor_hist_adr_usd           4705359
prop_country_id                      0
prop_id                              0
prop_starrating                      0
prop_review_score                 7364
prop_brand_bool                      0
prop_location_score1                 0
prop_location_score2           1090348
prop_log_historical_price            0
position                             0
price_usd                            0
promotion_flag                       0
srch_destination_id                  0
srch_length_of_stay                  0
srch_booking_window                  0
srch_adults_count                    0
srch_children_count                  0
srch_room_count                      0
srch_saturday_night_bool             0
srch_query_affinity_score      4640941
orig_destination_distance      1607782
random_bool                          0
comp1_rate                     4838417
comp1_inv                      4828788
comp1_rate_percent_diff        4863908
comp2_rate                     2933675
comp2_inv                      2828078
comp2_rate_percent_diff        4402109
comp3_rate                     3424059
comp3_inv                      3307357
comp3_rate_percent_diff        4485550
comp4_rate                     4650969
comp4_inv                      4614684
comp4_rate_percent_diff        4827261
comp5_rate                     2735974
comp5_inv                      2598327
comp5_rate_percent_diff        4117248
comp6_rate                     4718190
comp6_inv                      4697371
comp6_rate_percent_diff        4862173
comp7_rate                     4642999
comp7_inv                      4601925
comp7_rate_percent_diff        4819832
comp8_rate                     3041693
comp8_inv                      2970844
comp8_rate_percent_diff        4343617
click_bool                           0
gross_bookings_usd             4819957
booking_bool                         0
dtype: int64

In [8]:
df.srch_id.nunique()

199795

In [9]:
df.groupby("srch_id").size().describe()

count    199795.000000
mean         24.817173
std           9.113335
min           5.000000
25%          18.000000
50%          29.000000
75%          32.000000
max          38.000000
dtype: float64

In [33]:
df.srch_id.count()

4958347

In [1]:
df.groupby("prop_id").size()

NameError: name 'df' is not defined

In [36]:
print(2)

2